= 사용설명서

== 회원 서비스

회원가입::
웹사이트 오른쪽 상단의 '회원가입'을 클릭하고 필요한 정보를 입력합니다.
회원가입 완료 시 기본적으로 100만 포인트가 지급됩니다.
이미 존재하는 이이디를 입력할 경우 에러 페이지로 이동합니다.

로그인::
웹사이트 오른쪽 상단의 '로그인' 버튼을 클릭하고
아이디와 비밀번호를 입력합니다.
(admin 계정 id : admin pw ; 12345, user 계정 id : user pw : 12345)
로그인 성공 시 60분 동안 세션이 유지됩니다.

로그아웃::
로그인을 한 상태에서
웹사이트 오른쪽 상단의 '로그아웃' 버튼을 클릭합니다.


== 마이페이지 서비스


마이페이지 조회::
로그인 후, 왼쪽 상단의 '마이페이지' 클릭합니다.
UserName, User Birth, User Auth, User Point,
Created At, Lastest Login At 정보를 확인할 수있습니다.

유저 정보 수정하기 ::
마이페이지에서 '유저정보수정하기' 클릭합니다.
Form을 작성하고 '제출' 버튼을 클릭합니다.

주소 등록하기::
마이페이지에서 '주소 등록하기' 버튼을 클릭하고
주소를 입력합니다.
등록된 주소는 마이페이지에서 조회, 수정, 삭제 할 수있습니다.
(중복된 addressNickname을 등록할 시 에러페이지로 이동합니다)

회원탈퇴::

마이페이지에서 '회원탈퇴' 버튼을 클릭합니다.
로그아웃을 동시에 진행합니다.


== 관리자 서비스


관리자 페이지 조회::
admin 계정으로 로그인 후 웹페이지 왼쪽상단의 '관리자 페이지' 클릭합니다.

상품 관리 ::
관리자 페이지에서 '상품 관리'를 클릭하면
상품을 등록, 수정, 삭제할 수 있습니다.

상품 등록하기 ::
'상품 등록하기' 버튼 클릭 후 Form을 채운뒤 제출
상품은 반드시 하나의 categoryID를 가집니다.

상품 수정하기 ::
'상품 관리' 페이지에서 각 상품의 우측에 수정하기 버튼을 클릭합니다.
이미지의 경우 새로운 이미지 업로드 하지않으면 기존 이미지로 유지됩니다.
Form 작성 후 '제출'버튼을 클릭합니다.

상품 삭제하기 ::
'상품 관리' 페이지에서 각 상품의 우측에 삭제하기 버튼을 클릭합니다.


== 상품 서비스


상품 조회::
웹사이트 왼쪽 상단 'Home' 버튼을 클릭합니다.
초기 index 페이지에 모든 카테고리의 상품을 노출합니다.
카테고리 ID를 선택하고 'submit' 버튼을 클릭하면
해당 카테고리의 상품들을 노출합니다.
상품의 이미지가 존재하지 않으면 no-image.png 이미지가 출력됩니다.


== 장바구니 서비스


장바구니 추가::
웹사이트 index 페이지에서 각 상품 목록의 '장바구니에 '추가 버튼을 클릭하면
해당 상품이 장바구니에 담깁니다.
이미 장바구니에 담긴 상품은 중복으로 담을 수 없습니다.
(중복된 productId 상품을 추가할 시 에러 페이지 이동)

장바구니 조회::
로그인 후, 웹사이트 왼쪽 상단 '장바구니' 클릭합니다.
modelName, UnitCost, Quantity, Total cost 및
장바구니에 담긴 총 금액을 확인 할 수 있습니다.

장바구니 상품 수량 조절::
장바구니의 각 상품에서 Controll Quantity 항목에서 up/down으로 조절합니다.

장바구니 상품 삭제::
장바구니의 각 상품에서 Delete product 항목의 delete 버튼을 클릭합니다.


== 주문 및 결제 서비스


주문하기::
장바구니 페이지에서 '주문하기' 버튼을 클릭합니다.
user의 point가 총 금액보다 작으면 결제가 반영되지 않습니다.
주문 완료된 상품은 장바구니에서 삭제 됩니다.
주문 완료 시 일정시간 이후 주문 금액의 10%가 포인트로 적립됩니다.
주문 완료 시 order sheet 페이지로 이동합니다.
order sheet 페이지는 주문 상품의 가격, 사용자의 잔여포인트, 추후 적립될 포인트가 출력됩니다.


== 포인트 서비스


포인트 적립:: 매일 첫 로그인 시 1만 포인트가 자동적으로 적립됩니다.


==테스트 코드

각 table의 repository에 대한 테스트 코드가 있습니다.
